### ISSUE TITLE
Submit to mainline Emacs

### ISSUE THREAD

**Issue by skangas** [Fuco1/eshell-bookmark#1]
This is a very cool idea, and something which should definitely be in mainline Emacs to benefit even more users.  I suggest you re-package this as an Emacs patch and submit it to bug-gnu-emacs@gnu.org.

Please see here for more information:
https://github.com/emacs-mirror/emacs/blob/master/CONTRIBUTE

Best regards,
Stefan Kangas

**Comment by Fuco1** [comment]
Hi.  To be completely honest, I'm not interested in contributing to Emacs.  Feel free to take the patch and do it yourself, the licence permits it.

**Comment by dgutov** [comment]
Hi @Fuco1.

Could you explain why, in a few words? Just for us to have a rough idea.

**Comment by priyadarshan** [comment]
FYI, this ticket was cited [on emacs-devel](https://lists.gnu.org/archive/html/emacs-devel/2020-05/msg02356.html)

**Comment by Fuco1** [comment]
@dgutov I'm not interested in the politics.  When RMS has no problem fucking up the entire ecosystem outside "core Emacs" (hint: there is no such thing), I don't want to be a part of that culture.

The Emacs Devel sounds bitter as hell, probably because there's thousands of people doing Emacs development on GitHub and 10 people on the mailing list :man_shrugging:.

Example: he would happily introduce incompatible prefixes because "packages outside Emacs" don't exist and break millions of users.  This shows profound disregard of value of your user's time.

**Comment by dgutov** [comment]
> Example: he would happily introduce incompatible prefixes because "packages outside Emacs" don't exist and break millions of users. This shows profound lack of disregard of value of your user's time.

It's not so bad, though, and more a result of ignorance rather than hostility. Which we've made some effort to dispel. So you might be glad to hear that whatever plans you were referring to, are unlikely to happen now.

**Comment by Fuco1** [comment]
That's good to hear indeed.  And I'm generally happy with how Emacs is moving forward.

**Comment by skangas** [comment]
> That's good to hear indeed. And I'm generally happy with how Emacs is moving forward.

I've now implemented this in a different way on the master branch, so this request is no longer relevant.

Thanks for your time, I'm closing this now.
